---
title: "Final Project"
output: html_notebook
---

***Statistical Computing***

***Name: Long Ngo***




```{r}
library(caret)
library(glmnet)
library(ncvreg)
library(L0Learn)
library(ncpen)
library(doParallel)
```


```{r}
df = read.csv("C:/Users/Monolith/Downloads/BankChurners/BankChurners_clean.csv")
```

```{r}
head(df)
```

```{r}
df = drop(df[-1])
```



```{r}
head(df)
```


```{r}
indices = createDataPartition(df$Attrition_Flag, times = 1,p = 0.7,list = FALSE)
```

```{r}
X.train = drop(df[-1])[indices,]
y.train = df$Attrition_Flag[indices]
X.test = drop(df[-1])[-indices,]
y.test = df$Attrition_Flag[-indices]
```


```{r}
X.train.matrix = as.matrix(X.train)
```

```{r}
X.train.matrix
```


```{r}
time.start = Sys.time()
mcp = cv.ncvreg(as.matrix(X.train), y.train, family ="binomial", lambda = 0.1)
time.stop = Sys.time()
timerun.mcp = time.stop - time.start
```


```{r}
time.start = Sys.time()
scad = cv.ncvreg(as.matrix(X.train), y.train, family ="binomial",penalty="SCAD")
time.stop = Sys.time()
timerun.scad = time.stop - time.start
```

```{r}
time.start = Sys.time()
lasso.ncvreg = cv.ncvreg(as.matrix(X.train), y.train, family ="binomial",penalty="lasso")
time.stop = Sys.time()
timerun.lasso.ncvreg = time.stop - time.start
```


```{r}
time.start = Sys.time()
lasso.glm = cv.glmnet(as.matrix(X.train), y.train, family ="binomial",alpha=1,lambda=mcp$lambda, type.measure="class")
time.stop = Sys.time()
timerun.lasso.glm = time.stop - time.start
```


```{r}
timerun.lasso.ncvreg
timerun.mcp
timerun.scad
timerun.lasso.glm
```



```{r}
y.pred.mcp = predict(mcp, as.matrix(X.test), lambda=mcp$lambda.min, type = "class")
y.pred.lasso.ncvreg = predict(lasso.nvcreg, as.matrix(X.test), lambda=lasso.ncvreg$lambda.min, type = "class")
y.pred.scad = predict(scad, as.matrix(X.test), lambda=scad$lambda.min, type = "class")
y.pred.lasso.glm = predict(lasso.glm, as.matrix(X.test), s=lasso.glm$lambda.min, type = "class")
```

```{r}
mcp$lambda
```


```{r}
summary(mcp, lambda=mcp$lambda.min)
summary(scad, lambda=scad$lambda.min)
summary(lasso.nvcreg, lambda=lasso.nvcreg$lambda.min)
```

```{r}
lasso.glm
```

```{r}
mcp$lambda
```


```{r}
plot(mcp, type='pred')
plot(scad, type='pred')
plot(lasso.ncvreg, type='pred')
plot(lasso.glm)
```



```{r}
confusionMatrix(factor(y.test),factor(y.pred.mcp))
```

```{r}
confusionMatrix(factor(y.test),factor(y.pred.scad))
```

```{r}
confusionMatrix(factor(y.test),factor(y.pred.lasso.ncvreg))
```


```{r}
confusionMatrix(factor(y.test),factor(y.pred.lasso.glm))
```


```{r}
userLambda <- list()
userLambda[[1]] = seq(0.05,0.2,length=100)
```



```{r}
time.start = Sys.time()
ss = L0Learn.cvfit(as.matrix(X.train), y.train, nFolds=10, autoLambda=FALSE, loss="Logistic", penalty="L0", lambdaGrid=list(mcp$lambda))
time.stop = Sys.time()
timerun.ss = time.stop - time.start
```

```{r}
timerun.ss
```


```{r}
print(ss)
```

```{r}
lapply(ss$cvMeans,min)
```

```{r}
ss$fit$lambda
```


```{r}
#optimalGammaIndex = 5 # index of the optimal gamma identified previously
optimalLambdaIndex = which.min(ss$cvMeans[[1]])
```

```{r}
optimalLambdaIndex
```
```{r}
optimalLambda = ss$fit$lambda[[1]][optimalLambdaIndex]
optimalLambda
```


```{r}
coef(ss, lambda=optimalLambda)
```


```{r}
y.pred.ss = predict(ss, newx=as.matrix(X.test), lambda=optimalLambda)
```


```{r}
y.pred.ss = as.vector(y.pred.ss)
```

```{r}
y.pred.ss[y.pred.ss>0.5]=1
y.pred.ss[y.pred.ss<=0.5]=0
```


```{r}
confusionMatrix(factor(y.pred.ss),factor(y.test))
```


